// Generated by LiveScript 1.2.0
(function(){
  var express, nunjucks, path, morgan, googleSpreadsheets, favicon, i18n, app, server;
  express = require('express');
  nunjucks = require('nunjucks');
  path = require('path');
  morgan = require('morgan');
  googleSpreadsheets = require('google-spreadsheets');
  favicon = require('static-favicon');
  i18n = require('i18n-abide');
  app = express();
  app.use(function(req, res, next){
    if (/zh-TW$/.exec(req.url) || /en-US$/.exec(req.url)) {
      res.redirect(req.url + "/");
    }
    return next();
  });
  app.set('views', path.join(__dirname, 'views'));
  app.use(favicon());
  app.use(morgan('dev'));
  app.use(express['static'](path.join(__dirname, 'frontend/public')));
  app.use(i18n.abide({
    supported_languages: ["en-US", "zh-TW"],
    default_lang: "zh-TW",
    translation_directory: "locale",
    locale_on_url: true
  }));
  app.set('port', process.env.PORT || 3000);
  nunjucks.configure(app.get('views'), {
    autoescape: true,
    express: app
  });
  ['index', 'about', 'partner', 'contact', 'accelerate', 'events', 'alumni', 'apply'].map(function(it){
    return app.get("/" + it + ".html", function(req, res){
      return res.render(it + ".html", {
        ENV: process.env.NODE_ENV,
        currentLocale: req.locale,
        currentPath: req.url
      });
    });
  });
  app.get('/', function(req, res){
    return res.render("index.html", {
      ENV: process.env.NODE_ENV,
      currentLocale: req.locale,
      currentPath: req.url
    });
  });
  app.get('/events.json', function(req, res){
    var GoogleSpreadsheet;
    GoogleSpreadsheet = googleSpreadsheets;
    return GoogleSpreadsheet.rows({
      key: '1uQsCyyNK3VVdSgTI_tEywA9OhuQdL1BW6RQ2tBjt9wY',
      worksheet: 1
    }, function(err, rows){
      var events, i$, len$, row;
      if (err) {
        console.error;
        return res.json([]);
      } else {
        events = [];
        for (i$ = 0, len$ = rows.length; i$ < len$; ++i$) {
          row = rows[i$];
          events.push({
            title: row.title,
            url: row.url,
            start: typeof row.start === 'string' && row.start || null,
            end: typeof row.end === 'string' && row.end || null
          });
        }
        return res.json(events);
      }
    });
  });
  app.get('/sitemap.xml', function(req, res){
    return res.render("sitemap.xml");
  });
  server = app.listen(app.get('port'), function(){
    return console.log('Express server listening on port ' + server.address().port);
  });
}).call(this);
